# Generated by Django 3.2.7 on 2021-10-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='symbol',
            field=models.CharField(default=' ', max_length=1),
            preserve_default=False,
        ),
    ]
